version: "2"
services:
  app:
    image: brennolyrio/trabalho:1.0
    links:
      - db  
    ports:
      - "5000:5000"
    depends_on:
      - db
      - adminer

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - '8080:8080'